name: Manual Self Approve PR Action
description: Allows approving of your own PRs.

on:
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI
    inputs:
      pr_number:
        description: "Pull Request Number to Approve"
        required: true
        type: number

jobs:
  self-approval-action:
    runs-on: ubuntu-latest
    steps:
      - name: Self-Approve Action
        uses: ./.github/actions/self-approval
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          client_id: ${{ secrets.SELF_APPROVE_PR_APP_ID  }}
          private_key: ${{ secrets.SELF_APPROVE_PR_APP_PRIVATE_KEY  }}
          installation_id: ${{ secrets.SELF_APPROVE_PR_APP_INSTALLATION_ID  }}
          pr_number: ${{ inputs.pr_number }}