name: Self Approve PR Action
description: Allows approving of your own PRs.

on:
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI
    inputs:
      pr_number:
        description: "Pull Request Number to Approve"
        required: true
        type: number

jobs:
  self-approval-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Self-Approve Action
        uses: ./../actions/self-approval
        with:
          client_id: ${{ secrets.SELF_APPROVE_PR_APP_ID  }}
          private_key: ${{ secrets.SELF_APPROVE_PR_APP_PRIVATE_KEY  }}
          installation_id: ${{ secrets.SELF_APPROVE_PR_APP_INSTALLATION_ID  }}
          pr_number: ${{ inputs.pr_number }}